import Head from 'next/head'
import 'antd/dist/reset.css';
import {Button, DatePicker, Space, Steps} from "antd"


export default function Home() {
  const description = 'This is a description.';

  return (
    <>
      <Head>
        <title>demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
      <h1>antd version: 1111</h1>
      <Space>
        <DatePicker />
        <Button type="primary">Primary Button</Button>
      </Space>
        <Steps
    direction="vertical"
    size="small"
    current={1}
    items={[
      { title: 'Finished', description },
      {
        title: 'In Progress',
        description,
      },
      {
        title: 'Waiting',
        description,
      },
    ]}
  />
    </div>
    </>
  )
}
